import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import Header from "@/components/navigation/Header";
import Footer from "@/components/navigation/Footer";
import Providers from "@/context/Providers";
import {AppToastProvider} from "@/components/ui/Toast/ToastProvider";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Retro Pop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
      <Providers>
          <AppToastProvider>
              <Header/>
              {children}
              <Footer/>
          </AppToastProvider>
      </Providers>
      </body>
      </html>
  );
}
